version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-19c
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0.22
    container_name: mysql-8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local
  mysql-data:
    driver: local
